//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csvy.Action.Implementation.Mstsc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csvy.Action.Implementation.Mstsc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mstsc.exe.
        /// </summary>
        internal static string MSTSC_BINARY {
            get {
                return ResourceManager.GetString("MSTSC_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##DOMAIN##.
        /// </summary>
        internal static string MSTSC_DOMAIN_TOKEN {
            get {
                return ResourceManager.GetString("MSTSC_DOMAIN_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76.
        /// </summary>
        internal static string MSTSC_REG_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("MSTSC_REG_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Terminal Server Client\LocalDevices.
        /// </summary>
        internal static string MSTSC_REG_KEY {
            get {
                return ResourceManager.GetString("MSTSC_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##SERVER##.
        /// </summary>
        internal static string MSTSC_SERVER_TOKEN {
            get {
                return ResourceManager.GetString("MSTSC_SERVER_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##USER##.
        /// </summary>
        internal static string MSTSC_USER_TOKEN {
            get {
                return ResourceManager.GetString("MSTSC_USER_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RdpTemplate File:
        ///screen mode Id:i:2
        ///desktopwidth:i:1280
        ///desktopheight:i:1024
        ///session bpp:i:16
        ///winposstr:s:0,1,1341,62,2434,863
        ///full address:s:##SERVER##
        ///compression:i:1
        ///keyboardhook:i:2
        ///audiomode:i:0
        ///redirectdrives:i:0
        ///redirectprinters:i:1
        ///redirectcomports:i:0
        ///redirectsmartcards:i:1
        ///displayconnectionbar:i:1
        ///autoreconnection enabled:i:0
        ///username:s:##USER##
        ///domain:s:##DOMAIN##
        ///alternate shell:s:
        ///shell working directory:s:
        ///disable wallpaper:i:1
        ///disable full window drag:i:1
        ///disable menu a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RdpTemplate {
            get {
                return ResourceManager.GetString("RdpTemplate", resourceCulture);
            }
        }
    }
}
